### ISSUE TITLE
IDX10214: Audience validation failed. Audiences:  Did not match: validationParameters.ValidAudience or validationParameters.ValidAudiences: 'null'.

### ISSUE THREAD

**Issue by anit05** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#11]
Hi I have a javascript client that generates access token issued by Azure AD B2C that i am using to access one of the api (application at my Azure AD B2C directory).
API is built in asp.net core.

But when i am using the token to access secure resources , it is throwing the error Invalid audience.

My API configuration is :

  app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                //AutomaticAuthenticate = true,
                //AutomaticChallenge = true,
                //Authority = String.Format(Configuration["AzureAd:AadInstance"], Configuration["AzureAD:Tenant"]),
                //Audience = Configuration["AzureAd:Audience"],

                MetadataAddress = string.Format("https://login.microsoftonline.com/{0}/v2.0/.well-known/openid-configuration?p={1}",
                Configuration["AzureAD:Tenant"], "B2C_1_Signin"),
                AuthenticationScheme = "B2C_1_Signin",
                Audience = Configuration["AzureAd:Audience"],
                Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = ctx =>
                    {
                        ctx.SkipToNextMiddleware();
                        return Task.FromResult(0);
                    }
                }
            });

I am not getting where to add audience in client side. 

What should i do ?

And I am little confused about Audience. What it is all about  and the fact that i am not able to find where to specify Audience in my JS app, how it should be handled ?

**Comment by orsolli** [comment]
The content of the jwt.body should contain a property calld "aud" and the value of that should be the same as the AzureAd:Audience setting.

But according to your error message, AzureAd:Audience may be null

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2
