### ISSUE TITLE
Claims in Access token

### ISSUE THREAD

**Issue by anit05** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#12]
Hi
I have a JavaScript app that makes call to my azure ad b2c account and gets access token that will be used to call another API.

In my sign in policies, i have added email to the claims to be returned.
When i use token to access secure resources of API, it works fine but i can not find email claim there.
There is name claim and some other as well.

Moreover i also want to return custom claims such as role. How do i assign roles to users there and return that in access token.

Please also let me know if i need to share anything related .
Thanks

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2
