### ISSUE TITLE
Great sample app, except I want to split my SPA from Web API

### ISSUE THREAD

**Issue by bkwdesign** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#13]
So glad I found this sample, as I don't want to learn angular just yet.

I was readily able to deploy to Azure, and successfully configured the AD tenant registration, per the instructions in your README. 

But, is it typical to have a SPA and a Web API share the same AD tenant App Registration?

Now that I'm wanting to make a SPA on one domain, and have it talk to a CORS-enabled Web API, I'm struggling getting everything to work. I know, from other research, to register them separately, and that I need to specify in my SPA registration that it should be allowed access to my Web API.. and I've clicked 'Grant Permissions', etc. - but all I get is `401 Not Authorized`. 

I'm also using RBAC, fwiw, so my Web API middleware looks like this:

```
   new WindowsAzureActiveDirectoryBearerAuthenticationOptions
   {
       Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
       TokenValidationParameters = new TokenValidationParameters
       {
           ValidAudience = ConfigurationManager.AppSettings["ida:Audience"],
           RoleClaimType = "roles"
       },
   });
```
When I decode my bearer token at [jwt.io](http://jwt.io) I can see the token I'm getting in ADAL.js is missing it's roles claim. I just don't know why.

**Comment by bkwdesign** [comment]
OK, I think this was the sample I was originally after... but didn't know how to google it yet due to my newness to OAuth and OpenID Connect...

https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect

**Comment by navyasric** [comment]
@bkwdesign Thank you for the feedback and glad you found the sample useful. For your case of having a CORS enabled web api with a SPA, you can refer to this sample: https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi

Closing this issue for now. Please reopen if it is not resolved.
