### ISSUE TITLE
Step 5 not quite right

### ISSUE THREAD

**Issue by intelogymartin** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#17]
I have been trying this sample and was unable to get it to work. In step 5 it says you can sign in by "either clicking on the sign in link on the top right corner, or by clicking directly on the Todo List tab". 
I was clicking on the Todo tab and always got an error message saying the "The reply url specified in the request does not match the reply urls configured for the application". I later realised the Login link works as expected. I found I could get the Todo link to work by adding https://localhost:44302/#TodoList to the list of Reply URLs in the App Registration.
I'm new to this so don't want to make assumptions but should the instructions say to add this extra Redirect URL or remove the part that says click Todo?

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2
