### ISSUE TITLE
This example does not work. Bad instructions

### ISSUE THREAD

**Issue by RafaelLiendo2409** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#19]
I followed the instructions to implement this example, but it does not work, something you do not put in the list. When I run the application I got this error:  AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'a2782399-c844-4c0c-8be4-ac142f284135'.

I seems an error in the app registration in Azure, but your instructions does no cover this or give more information. If I followed your instructions I got this error.  And the end this example is not working as your are explaning it here

**Comment by Thialala** [comment]
Hello,

In Azure AD, change the reply URL from https://localhost:44302 to  https://localhost:44302/#TodoList .

**Comment by jnlkds** [comment]
I tried the above and still get the error.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2
