### ISSUE TITLE
Mac OS, build warning

### ISSUE THREAD

**Issue by jefftanz** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#20]
Visual Studio 2017 Community Mac Version
clone repo -> Build

Build: 0 errors 1 warning

/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Web.Entity". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (MSB3245) (TodoSPA)

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2
