### ISSUE TITLE
Application not working as advertised

### ISSUE THREAD

**Issue by jnlkds** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#21]
I get the an error that Graph permissions needed to be added, which I can't find anything in the code which is identifying for additional permissions. 

More importantly,  the .Configure and the .Cleanup powershell scripts create the app known as SinglePageApp but when attempting to access I get the error ..

AADSTS50011: The reply uri specified in the request has an invalid scheme.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2
