### ISSUE TITLE
MS Edge does not work when account already logged in

### ISSUE THREAD

**Issue by mcqueene** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#26]
When already logged into an account, MS Edge doesn't load the credentials. When the login button is clicked the pop up for picking an account is presented. When that is selected the pop up sits there for a while and then throws a 404 not found (https://localhost:44302/null). This doesn't happen with Chrome.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2
