### ISSUE TITLE
Difficulty getting it to run

### ISSUE THREAD

**Issue by frankhoffy** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#4]
I had to change the web.config before this one would run for me.  I'm running VS2013 Ultimate.  It didn't like the mssqllocaldb parameter.  I had to change it to v11.0, like below.

```
<defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
  <parameters>
    <parameter value="v11.0" />
  </parameters>
</defaultConnectionFactory>
```

**Comment by dstrockis** [comment]
Sorry for the trouble Frank.  I'll look into making this fix.

**Comment by swsruthi** [comment]
I had the same issue
