### ISSUE TITLE
when users make an ajax call after the token is expired it renews the token but the renewed token is not used to make the call

### ISSUE THREAD

**Issue by swsruthi** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#5]
when ajax call is made after token is expired. acquireToken is renewing the token but we receive ADAL error. because token is empty. See attached. Next call will fetch the token from cache. 

I expected after renew the token should be updated. Am I doing something wrong?

![webapp5consoleapp_adalerror](https://cloud.githubusercontent.com/assets/12418449/7598882/4089df86-f8c3-11e4-8b95-166b9a8e280a.JPG)

**Comment by swsruthi** [comment]
To give more details, I was debugging the adal.js in handle window call back (handleWindowCallback)
 Line 742
if (requestInfo.requestType === this.REQUEST_TYPE.RENEW_TOKEN) {
            callback(this._getItem(this.CONSTANTS.STORAGE.ERROR_DESCRIPTION), requestInfo.parameters[this.CONSTANTS.ACCESS_TOKEN]);
            return;
        }

if look at values in requestInfo.parameters there is no access_token hence it is empty.
and on renew we see ADAL error occurred. if you run the application after soemtime it should renew the token but the renewed token is not passed to the callback.

Can this be corrected?

**Comment by dstrockis** [comment]
I'll have to dig into this one a bit and get back to you. Thanks @swsruthi

**Comment by janerivi** [comment]
We also experience this issue and made a workaround making an extra call. I hope you can look into it!

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2
