### ISSUE TITLE
repo referenced for where adal.js is being maintained is not found

### ISSUE THREAD

**Issue by myusrn** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi#7]
The readme for this sample suggests that the repo where active-directory-javascript-singlepageapp-dotnet-webapi/TodoSPA/App/Scripts/adal.js is being maintained is [https://github.com/Azure-Samples/azure-activedirectory-library-for-js](https://github.com/Azure-Samples/azure-activedirectory-library-for-js) but when I visit that link I get a 404 resource not found.

Has that been moved or dropped in lieu of just maintaining that adal.js source file here in this sample directly?

**Comment by danieldobalian** [comment]
Fixed.
